[package]
name = "sv1-custom-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
log = "0.4"
serde = { version = "1.0.89", features = ["derive", "alloc"], default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
tracing = "0.1"
tracing-subscriber = "0.3"
prometheus = "0.13"
warp = "0.3"
hyper = { version = "0.14", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
hex = "0.4.3"
cdk = { git = "https://github.com/vnprc/cdk", branch = "get_blinded_secrets" }
rand = "0.8.5"
bitcoin = "0.30"